### PR TITLE
Fix significantly outdated dependencies and security vulnerabilities

### LINKED ISSUE #19: VULNERABILITY: Denial Of Service in superagent < 3.7.0
│ Low           │ Large gzip Denial of Service                                 │
│ Package       │ superagent                                                   │
│ Patched in    │ >=3.7.0                                                      │
│ Dependency of │ commercecloud-ocapi-client                                   │
│ Path          │ commercecloud-ocapi-client > superagent                      │
│ More info     │ https://npmjs.com/advisories/479                             │

### PR DESCRIPTION
**Pull request by agrohs**
# Description

This PR includes updates to several outdated dependencies (including a few w significant security vulnerabilities in the old versions).

Fixes #19 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Changes

.babelrc, rollup.config.js and package.json script updates related the following package updates.

_Minor versions updates:_
"atob": "^2.0.3">"^2.1.2"
"btoa": "^1.1.2">"^1.2.1"
"eslint-import-resolver-webpack": "^0.8.3">"eslint-import-resolver-webpack": "^0.11.1"
"eslint-plugin-import": "2.3.0">"eslint-plugin-import": "^2.17.2"
"express": "^4.16.2">"express": "^4.17.0"
"jsdoc": "^3.4.3">"jsdoc": "^3.6.2"
"mobify-code-style": "2.8.1">"mobify-code-style": "^2.8.4"

_Major version updates:_
"superagent": "3.5.2">"^5.0.5"
"babel-cli": "^6.24.1">"@babel/cli": "^7.4.4"
"babel-core": "6.18.0">"@babel/core": "^7.4.5"
"babel-preset-env": "^1.6.1">"@babel/preset-env": "^7.4.5"
"eslint": "3.19.0">"eslint": "^5.16.0"
"mocha": "~2.3.4">"mocha": "^6.1.4"
"rollup": "^0.49.3">"rollup": "^1.12.3"
"rollup-plugin-babel": "^3.0.2">"rollup-plugin-babel": "^4.3.2"
"rollup-plugin-commonjs": "^8.2.6">"rollup-plugin-commonjs": "^10.0.0"
"rollup-plugin-node-resolve": "^3.0.0">"rollup-plugin-node-resolve": "^5.0.0"
"sinon": "1.17.3">"sinon": "^7.3.2"

_Remove dependencies (should no longer be needed):_
"babel-plugin-external-helpers": "^6.22.0"

_Additional dependencies (required as peer for updated packages above - or for testing):_
"@babel/register": "^7.4.4"
"webpack": "^4.32.2"

# How to test this PR?

Ran full test suite using `npm run test` (including updating from test config in package.json from babel-core/register to @babel/register)

**IMPORTANT**: The following 2 existing tests failed due to coding issues in existing test (CustomersApi.spec.js) that are now flagged by the newer/updated version of "mocha" (Error: Resolution method is overspecified. Specify a callback *or* return a Promise). I have gone ahead and fixed these two issues but would love an extra pair of eyes on them as they are the only changes I needed to make to the tests in order to pass.
FAILED:
Screen Shot 2019-05-23 at 11 29 57 AM
UPDATED/PASSED:
Screen Shot 2019-05-23 at 11 47 29 AM

NOTE: there are also few existing tests that throw an UnhandledPromiseRejectionWarning and should be addressed in the core code, but they appeared in existing test suite run before making any changes 
Screen Shot 2019-05-23 at 11 44 15 AM

# Checklist:

- [x] My code follows the style guidelines of this project (`npm run lint`)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (`README.md` and `CHANGELOG.md`)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes (`npm test`)

### CODE REVIEW

**Comment by agrohs** [comment]
As per my other note on #19, I'd also suggest adding something like [Renovate(bot)](https://github.com/apps/renovate) to this repo go forward. It will automatically create pull requests for manual review/consideration each time one of the dependencies in this project has a version update. This can help avoid major updates to a bunch of packages all in one commit/PR.

Just my 2 cents!
Adam

**Comment by johnboxall** [comment]
Well that's cool 🎈 – thanks @agrohs!

bitmoji

I'll see if I can find time to review over the next week two weeks 🕐

**Comment by agrohs** [comment]
As an aside, I have a separate PR ready to go that brings in generation of, storage and validation/checking of oAuth tokens for oAuth required requests to the Shop API (using it locally within our project via the fork for now). It is branched starting from the above new packages/PR as the starting point so will keep it in my fork and wait to submit that PR till this one is reviewed/cleared but just wanted to send a heads up!

**Comment by johnboxall** [comment]
> generation of, storage and validation/checking of oAuth tokens for oAuth required requests to the Shop API

@agrohs – well that also sounds pretty cool :)

We use this package both client & server-side (in browser & in Node) – as a side effect of that, we also manage JWTs outside the scope of this package.

I'd be really interested in seeing what you're doing and I think it would be valuable to document strategies to persist tokens but we'd probably have to put our thinking caps on a bit around whether we'd accept a patch that added storage.

**Comment by agrohs** [comment]
The storage persistence actually already takes into account both running client and server side actually (based on a similar implementation for another API we work with). It has pluggable storage factories and contains 2 implementations (one for in-memory storage and one for local storage that uses node-localstorage if running server side or the browser’s local storage if being used client side)!

**Comment by agrohs** [comment]
Just checking in on this PR?

**Comment by bendvc** [comment]
@agrohs Going to close this PR. I was not away of it when updating the dependancies in another. If you are interested you can see what was changed here --> https://github.com/mobify/commercecloud-ocapi-client/pull/23

**Pull request closed without merging**
